// SPDX-License-Identifier: MIT OR Apache-2.0

//! The credential lifecycle (§9.1–§9.3): creation, epoch certification and rollover, key
//! destruction, and planned migration — sequenced here, once, against the two ports.
//!
//! # The engine sequences; the host implements
//!
//! Every operation in this module drives [`KeyStore`] and [`SecureStorage`] directly rather
//! than returning instructions for the host to carry out. The ordering *is* the security
//! property: destroying an epoch key when its epoch ends is §9.1's forward secrecy, storing
//! nothing before the root exists is what keeps a half-created credential impossible, and a
//! host asked to remember either would eventually forget. One audited implementation of the
//! sequencing is the same argument §6.5 makes for one shared circuit.
//!
//! # Randomness is a parameter, not a port
//!
//! The engine holds no RNG for the same reason it holds no clock: a trait would buy nothing
//! over the value itself and would cost testability. Fresh key material arrives as
//! [`FreshEntropy`], generated by the host's CSPRNG, consumed exactly once. §5.1's rule
//! rides on the type: fresh and independent **per agora**, never derived from a shared seed,
//! however convenient a shared seed would make backup. The reference `SoftwareKeyStore`
//! derives everything from one seed and is named unfit for production custody for exactly
//! that reason.
//!
//! One asymmetry is deliberate. `sk_cred` and `r_root` are uniform bytes in any plausible
//! construction — they exist to be hash preimages — so entropy *is* the secret. An epoch
//! keypair has a shape chosen by the signature scheme, which is fixed with the proving
//! system (§6.5), so [`roll_epoch`] takes the secret and public halves as the host's scheme
//! produced them rather than pretending to derive one from the other.
//!
//! # What failure leaves behind
//!
//! Creation and migration store several slots; a failure part-way is unwound with
//! best-effort deletes so the member never holds a credential that half-exists. The one
//! thing that cannot be unwound is a root key already created in a hardware backend —
//! there is deliberately no destroy operation on [`KeyStore`] — and it does not need to be:
//! an orphaned root authorizes nothing, because its commitment never left the device.

use nymora_core::{
    AgoraId, Commitment, EpochCertPayload, MigrationCertPayload, MigrationHandoff, Nullifier,
    ProtocolError, SecretBytes, TagKey,
};
use nymora_core::{CredentialKey, Epoch, RootOpening};
use nymora_ports::{KeyStore, RootMaterialOut, RootMaterialWritten, SecureStorage, Slot};
use zeroize::Zeroizing;

#[cfg(feature = "provisional-algebraic-hash")]
use nymora_crypto::{commit, nullifier};

/// Fresh secret bytes from the host's CSPRNG, consumed exactly once.
///
/// This type exists to make an obligation visible at the call site: the bytes must be
/// freshly generated for this one use, independently **per agora** (§5.1), and never
/// derived, counted, reused, or restored from anywhere. Nothing can verify that — which is
/// why it is a named type with one construction path instead of a `[u8; 32]` that could
/// have come from anything.
///
/// Zeroized on drop and redacted in `Debug`, like every secret.
#[derive(Debug)]
pub struct FreshEntropy(SecretBytes<32>);

impl FreshEntropy {
    /// Wraps 32 freshly generated bytes.
    #[must_use]
    pub fn new(bytes: [u8; 32]) -> Self {
        Self(SecretBytes::new(bytes))
    }

    /// Copies the bytes out, consuming the wrapper.
    pub(crate) fn take(self) -> [u8; 32] {
        *self.0.expose()
    }
}

/// What [`create`] produced.
#[derive(Debug)]
pub struct Created {
    /// The credential's leaf, `Commit(pk_root, sk_cred, r_root, agora_id)` (§9.1) — what
    /// `credentials/init` submits for admission (§5.3).
    pub commitment: Commitment,
    /// How much of each caller buffer the root creation used, including whether the backend
    /// produced a hardware binding.
    pub root: RootMaterialWritten,
}

/// What [`complete_migration`] produced.
#[derive(Debug)]
pub struct Migrated {
    /// The successor's leaf, committing to the **same** `sk_cred` as the leaf it replaces
    /// (§9.3).
    pub commitment: Commitment,
    /// The migration nullifier `Hash(sk_cred, leaf_old, agora_id)` consuming the old leaf —
    /// submitted alongside the migration proof, spent in the migration-spend set (§9.1).
    pub spend: Nullifier,
}

/// The most epochs one rollover will sweep.
///
/// A bound exists so that a corrupted or mistyped epoch number becomes an error instead of
/// an unbounded delete loop; its value is unreachable legitimately, since epochs are at
/// least 24 hours (§9.1) and this many is centuries of continuous gap.
pub const MAX_EPOCH_GAP: u64 = 100_000;

/// Creates a credential for one agora: root authority, durable secrets, and the leaf.
///
/// The sequence is `create_root` first, stores second — nothing is persisted unless the
/// root exists — and a storage failure unwinds every slot already written before the error
/// is returned, so the member never holds a partial credential. The buffers receive the
/// root public key and the backend's binding, sized by the caller as [`KeyStore`] requires.
///
/// The returned commitment is the only value that leaves the device: Skiora receives it at
/// `credentials/init` and never the key material it commits to.
///
/// # Errors
///
/// Whatever the ports report, unchanged: [`ProtocolError::Unavailable`] where a backend or
/// the store could not act, [`ProtocolError::Malformed`] where a caller buffer is too
/// small.
#[cfg(feature = "provisional-algebraic-hash")]
pub fn create(
    agora: AgoraId,
    key_store: &dyn KeyStore,
    storage: &mut dyn SecureStorage,
    credential_key: FreshEntropy,
    root_opening: FreshEntropy,
    public_key: &mut [u8],
    binding: &mut [u8],
) -> Result<Created, ProtocolError> {
    let root = key_store.create_root(
        agora,
        RootMaterialOut {
            public_key: &mut *public_key,
            binding: &mut *binding,
        },
    )?;
    let pk_root = &public_key[..root.public_key];

    let sk_cred = CredentialKey::new(credential_key.take());
    let r_root = RootOpening::new(root_opening.take());
    let commitment = commit(pk_root, &sk_cred, &r_root, &agora);

    store_credential_material(storage, agora, &sk_cred, &r_root, pk_root)?;

    Ok(Created { commitment, root })
}

/// Stores the three durable slots, unwinding the ones already written on failure.
fn store_credential_material(
    storage: &mut dyn SecureStorage,
    agora: AgoraId,
    sk_cred: &CredentialKey,
    r_root: &RootOpening,
    pk_root: &[u8],
) -> Result<(), ProtocolError> {
    storage.store(agora, Slot::CredentialKey, sk_cred.expose())?;
    if let Err(error) = storage.store(agora, Slot::RootOpening, r_root.expose()) {
        let _ = storage.delete(agora, Slot::CredentialKey);
        return Err(error);
    }
    if let Err(error) = storage.store(agora, Slot::RootPublicKey, pk_root) {
        let _ = storage.delete(agora, Slot::RootOpening);
        let _ = storage.delete(agora, Slot::CredentialKey);
        return Err(error);
    }
    Ok(())
}

/// Destroys every epoch key and certificate for epochs that have ended.
///
/// Deletion is driven by the epoch **ending**, not by a successor being certified (§9.1,
/// proposal 0007): a member who wakes after any number of boundaries and does not act must
/// still end up holding no usable key, so this runs without certifying anything. The sweep
/// covers every epoch from the member's own cursor up to — excluding — `current`, leaning
/// on [`delete`](SecureStorage::delete)'s idempotence: sweeping twice, or sweeping epochs
/// that never held a key, is safe and indistinguishable from sweeping once.
///
/// The cursor is not advanced here — it records the last epoch *certified*, and re-sweeping
/// an already-clean range costs nothing.
///
/// # Errors
///
/// [`ProtocolError::Malformed`] if `current` is behind the cursor or implausibly far ahead
/// ([`MAX_EPOCH_GAP`]); storage errors unchanged. A failed sweep is safe to retry — nothing
/// is recorded about partial progress, so the next call covers the same range.
pub fn discard_expired(
    agora: AgoraId,
    storage: &mut dyn SecureStorage,
    current: Epoch,
) -> Result<(), ProtocolError> {
    let Some(cursor) = load_cursor(agora, storage)? else {
        return Ok(());
    };
    let mut epoch = checked_span(cursor, current)?;
    while epoch < current {
        storage.delete(agora, Slot::EpochKey(epoch))?;
        storage.delete(agora, Slot::EpochCert(epoch))?;
        // The span check bounds this walk, and `current` is a valid `Epoch`, so the
        // increment cannot overflow before the loop condition fails.
        epoch = Epoch::new(epoch.get() + 1);
    }
    Ok(())
}

/// Rolls the credential to `current`: sweeps ended epochs, certifies the fresh key, stores
/// it with its certificate, and advances the cursor.
///
/// The epoch keypair arrives as the host's signature scheme produced it — see the module
/// documentation for why the public half is not derived here. `record` is scratch for the
/// stored certificate record and must hold the public key, the signature, and two length
/// prefixes; the signature is written through [`KeyStore::sign_epoch_cert`], which may
/// prompt for user presence (§9.2).
///
/// Certifying the epoch the cursor already names is permitted and overwrites: nothing can
/// prevent a member holding two keys in one epoch (§9.1), and this store does not pretend
/// otherwise — it simply keeps the latest.
///
/// A member out of contact may call this with the last epoch it knows of and risk
/// rejection if the agora has advanced (§9.1); that is this same code path, not a special
/// case.
///
/// # Errors
///
/// As [`discard_expired`], plus whatever the signing backend reports. If storing the
/// cursor fails after the key and certificate landed, the state is usable and the *next*
/// roll re-sweeps from the old cursor — the error is still returned so the host can retry.
pub fn roll_epoch(
    agora: AgoraId,
    key_store: &dyn KeyStore,
    storage: &mut dyn SecureStorage,
    current: Epoch,
    epoch_secret: FreshEntropy,
    epoch_public_key: &[u8],
    record: &mut [u8],
) -> Result<(), ProtocolError> {
    if let Some(cursor) = load_cursor(agora, storage)? {
        if current != cursor {
            checked_span(cursor, current)?;
        }
    }

    // Sign before destroying anything: a refused prompt or a short buffer must leave the
    // credential exactly as it was.
    let record_len = sign_epoch_record(agora, key_store, current, epoch_public_key, record)?;

    discard_expired(agora, storage, current)?;

    let secret = epoch_secret.take();
    storage.store(agora, Slot::EpochKey(current), &secret)?;
    if let Err(error) = storage.store(agora, Slot::EpochCert(current), &record[..record_len]) {
        let _ = storage.delete(agora, Slot::EpochKey(current));
        return Err(error);
    }
    storage.store(agora, Slot::EpochCursor, &current.get().to_le_bytes())
}

/// Signs the canonical epoch-cert payload and assembles the stored record in `record`.
///
/// Record layout: `framed(epoch_public_key) ‖ framed(signature)` — the same length-framing
/// as every encoding in `nymora-core`. Local storage only; it never crosses
/// implementations, but a canonical layout costs nothing and keeps decoding strict.
fn sign_epoch_record(
    agora: AgoraId,
    key_store: &dyn KeyStore,
    epoch: Epoch,
    epoch_public_key: &[u8],
    record: &mut [u8],
) -> Result<usize, ProtocolError> {
    const PREFIX: usize = core::mem::size_of::<u64>();
    let pk_len = epoch_public_key.len();
    let sig_at = PREFIX + pk_len + PREFIX;
    if record.len() < sig_at {
        return Err(ProtocolError::Malformed);
    }

    record[..PREFIX].copy_from_slice(&(pk_len as u64).to_le_bytes());
    record[PREFIX..PREFIX + pk_len].copy_from_slice(epoch_public_key);

    let payload = EpochCertPayload {
        agora,
        epoch,
        epoch_public_key,
    };
    let sig_len = key_store.sign_epoch_cert(&payload, &mut record[sig_at..])?;
    record[PREFIX + pk_len..sig_at].copy_from_slice(&(sig_len as u64).to_le_bytes());
    Ok(sig_at + sig_len)
}

/// A stored epoch certificate record: the epoch public key and the root signature over its
/// canonical payload — the private witnesses a routine proof takes (§9.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EpochRecord<'a> {
    /// `pk_epoch`, exactly as certified. A private witness, never a public input (§9.1).
    pub public_key: &'a [u8],
    /// The root signature over the canonical [`EpochCertPayload`] encoding.
    pub signature: &'a [u8],
}

impl<'a> EpochRecord<'a> {
    /// Reads a record from its stored layout. Strict: truncation, overstated lengths, and
    /// trailing bytes are all [`ProtocolError::Malformed`].
    ///
    /// # Errors
    ///
    /// [`ProtocolError::Malformed`] for any input that is not exactly one valid record.
    pub fn decode(bytes: &'a [u8]) -> Result<Self, ProtocolError> {
        let mut rest = bytes;
        let public_key = take_framed(&mut rest)?;
        let signature = take_framed(&mut rest)?;
        if !rest.is_empty() {
            return Err(ProtocolError::Malformed);
        }
        Ok(Self {
            public_key,
            signature,
        })
    }
}

/// Loads and decodes the epoch record for `epoch`, or `None` where none is stored.
///
/// # Errors
///
/// Storage errors unchanged; [`ProtocolError::Malformed`] if the caller's buffer is too
/// small for the stored value, or [`ProtocolError::Unavailable`] if the stored bytes do not
/// decode — a corrupt record is an operational fault of the store, not a property of the
/// caller's input.
pub fn load_epoch_record<'a>(
    agora: AgoraId,
    storage: &dyn SecureStorage,
    epoch: Epoch,
    buffer: &'a mut [u8],
) -> Result<Option<EpochRecord<'a>>, ProtocolError> {
    let Some(len) = storage.load(agora, Slot::EpochCert(epoch), buffer)? else {
        return Ok(None);
    };
    match EpochRecord::decode(&buffer[..len]) {
        Ok(record) => Ok(Some(record)),
        Err(_) => Err(ProtocolError::Unavailable),
    }
}

/// Stores one epoch's routing tag key on broadcast receipt (§6.4).
///
/// Several epochs' keys are live at once: §11's revocation asymmetry means read capability
/// persists until the next broadcast, and older keys are what resolve older content. When
/// a key is *discarded* is a §6.4 retention question this phase deliberately does not
/// settle; nothing here deletes tag keys.
///
/// # Errors
///
/// Storage errors, unchanged.
pub fn store_tag_key(
    agora: AgoraId,
    storage: &mut dyn SecureStorage,
    epoch: Epoch,
    key: &TagKey,
) -> Result<(), ProtocolError> {
    storage.store(agora, Slot::TagKey(epoch), key.expose())
}

/// Creates the successor's root authority — the first step of a planned migration (§9.3).
///
/// The successor generates its keys *before* the old device signs anything: the returned
/// public key is what travels to the old device to be named in the migration certificate.
/// Nothing is stored yet — the successor holds no credential until
/// [`complete_migration`] — and this is the only `create_root` call the successor makes,
/// since a hardware backend cannot reproduce a key it is asked to create twice.
///
/// # Errors
///
/// See [`KeyStore::create_root`].
pub fn create_successor_root(
    agora: AgoraId,
    key_store: &dyn KeyStore,
    public_key: &mut [u8],
    binding: &mut [u8],
) -> Result<RootMaterialWritten, ProtocolError> {
    key_store.create_root(
        agora,
        RootMaterialOut {
            public_key,
            binding,
        },
    )
}

/// Authorizes a planned migration on the old device, producing the encoded handoff (§9.3).
///
/// Signs the canonical [`MigrationCertPayload`] over the successor's public key and writes
/// the [`MigrationHandoff`] — `sk_cred`, `r_root`, `pk_root`, the certificate — into
/// `out`, returning its length. That is everything the migration *proof* needs about the
/// predecessor, because the successor is the prover: the statement it proves opens the old
/// leaf, and the leaf itself is derived from these values rather than carried. The handoff
/// carries the durable secret; the transport rules in `nymora-core`'s handoff module are
/// the caller's obligations from this point.
///
/// Nothing is deleted here. The old leaf stays valid until the successor's migration is
/// verified and the spend enters the exclusion roots at the boundary (§9.3); when the old
/// device retires its local material is the host's decision, made after the successor is
/// confirmed, not a step this function can safely take for it.
///
/// # Errors
///
/// [`ProtocolError::Unavailable`] if no credential is stored for `agora` (or its stored
/// material is corrupt); [`ProtocolError::Malformed`] for short caller buffers; port errors
/// unchanged.
pub fn authorize_migration(
    agora: AgoraId,
    key_store: &dyn KeyStore,
    storage: &dyn SecureStorage,
    successor_public_key: &[u8],
    root_public_key: &mut [u8],
    signature: &mut [u8],
    out: &mut [u8],
) -> Result<usize, ProtocolError> {
    let sk_cred = CredentialKey::new(*load_secret32(agora, storage, Slot::CredentialKey)?);
    let r_root = RootOpening::new(*load_secret32(agora, storage, Slot::RootOpening)?);
    let pk_len = storage
        .load(agora, Slot::RootPublicKey, root_public_key)?
        .ok_or(ProtocolError::Unavailable)?;

    let payload = MigrationCertPayload {
        agora,
        successor_public_key,
    };
    let sig_len = key_store.sign_migration(&payload, signature)?;

    MigrationHandoff {
        agora,
        credential_key: sk_cred,
        root_opening: r_root,
        root_public_key: &root_public_key[..pk_len],
        migration_cert: &signature[..sig_len],
    }
    .encode(out)
}

/// Completes a planned migration on the successor device (§9.3).
///
/// Takes the decoded handoff, the public key from [`create_successor_root`], and a fresh
/// opening — `r_root` is regenerated because nothing requires it to survive, while
/// `sk_cred` carries because every count depends on it. Verifies the handoff names this
/// agora, assembles the successor leaf, derives the spend, and stores the durable slots
/// with the same unwind-on-failure contract as [`create`].
///
/// The returned pieces — new commitment, spend nullifier, plus the certificate the caller
/// already holds — are what `credentials/migrate` submits under the migration proof; the
/// proof itself is a later phase's interface.
///
/// # Errors
///
/// [`ProtocolError::Malformed`] if the handoff names a different agora — a handoff applied
/// to the wrong membership must fail before anything derives from it. Storage errors as
/// [`create`].
#[cfg(feature = "provisional-algebraic-hash")]
pub fn complete_migration(
    agora: AgoraId,
    storage: &mut dyn SecureStorage,
    handoff: &MigrationHandoff<'_>,
    root_public_key: &[u8],
    root_opening: FreshEntropy,
) -> Result<Migrated, ProtocolError> {
    if handoff.agora != agora {
        return Err(ProtocolError::Malformed);
    }

    let r_root = RootOpening::new(root_opening.take());
    let commitment = commit(root_public_key, &handoff.credential_key, &r_root, &agora);
    // The consumed leaf is derived from the handoff, never carried in it — a derived value
    // cannot disagree with the material the migration proof opens it with.
    let consumed_leaf = commit(
        handoff.root_public_key,
        &handoff.credential_key,
        &handoff.root_opening,
        &agora,
    );
    let spend = nullifier::migration(&handoff.credential_key, &consumed_leaf, &agora);

    store_credential_material(
        storage,
        agora,
        &handoff.credential_key,
        &r_root,
        root_public_key,
    )?;

    Ok(Migrated { commitment, spend })
}

/// Loads the member's epoch cursor, or `None` before the first certification.
fn load_cursor(
    agora: AgoraId,
    storage: &dyn SecureStorage,
) -> Result<Option<Epoch>, ProtocolError> {
    let mut bytes = [0u8; 8];
    match storage.load(agora, Slot::EpochCursor, &mut bytes)? {
        None => Ok(None),
        Some(8) => Ok(Some(Epoch::new(u64::from_le_bytes(bytes)))),
        // A cursor of the wrong width is store corruption, not caller input.
        Some(_) => Err(ProtocolError::Unavailable),
    }
}

/// Validates that `current` is at or ahead of `cursor` by a plausible amount, returning the
/// sweep's starting epoch.
fn checked_span(cursor: Epoch, current: Epoch) -> Result<Epoch, ProtocolError> {
    if current < cursor || current.get() - cursor.get() > MAX_EPOCH_GAP {
        return Err(ProtocolError::Malformed);
    }
    Ok(cursor)
}

/// Loads a 32-byte secret slot into a zeroizing buffer.
pub(crate) fn load_secret32(
    agora: AgoraId,
    storage: &dyn SecureStorage,
    slot: Slot,
) -> Result<Zeroizing<[u8; 32]>, ProtocolError> {
    let mut bytes = Zeroizing::new([0u8; 32]);
    match storage.load(agora, slot, &mut bytes[..])? {
        Some(32) => Ok(bytes),
        // Absent: the caller has no credential here. Wrong width: the store corrupted a
        // value this module wrote. Both are operational, neither is the caller's input.
        _ => Err(ProtocolError::Unavailable),
    }
}

/// Reads a length-prefixed field, advancing `rest`.
fn take_framed<'a>(rest: &mut &'a [u8]) -> Result<&'a [u8], ProtocolError> {
    const PREFIX: usize = core::mem::size_of::<u64>();
    let prefix = rest
        .get(..PREFIX)
        .ok_or(ProtocolError::Malformed)?
        .try_into()
        .map_err(|_| ProtocolError::Malformed)?;
    let len = usize::try_from(u64::from_le_bytes(prefix)).map_err(|_| ProtocolError::Malformed)?;
    let body = rest
        .get(PREFIX..PREFIX + len)
        .ok_or(ProtocolError::Malformed)?;
    *rest = &rest[PREFIX + len..];
    Ok(body)
}

#[cfg(test)]
mod tests {
    use super::*;
    use nymora_ports::SoftwareKeyStore;
    use std::collections::HashMap;
    use std::format;
    use std::vec;
    use std::vec::Vec;

    const AGORA_A: AgoraId = AgoraId::from_bytes([0x01; 32]);
    const AGORA_B: AgoraId = AgoraId::from_bytes([0x02; 32]);

    /// An in-memory `SecureStorage` that records every mutation, in order, and can be told
    /// to start failing after a number of stores — the double 3.5 of the phase plan asks
    /// for.
    #[derive(Default)]
    struct TestStore {
        values: HashMap<([u8; 32], Slot), Vec<u8>>,
        log: Vec<(char, Slot)>,
        stores_before_failure: Option<usize>,
    }

    impl SecureStorage for TestStore {
        fn store(&mut self, agora: AgoraId, slot: Slot, value: &[u8]) -> Result<(), ProtocolError> {
            if let Some(remaining) = &mut self.stores_before_failure {
                if *remaining == 0 {
                    return Err(ProtocolError::Unavailable);
                }
                *remaining -= 1;
            }
            self.log.push(('s', slot));
            self.values
                .insert((*agora.as_bytes(), slot), value.to_vec());
            Ok(())
        }

        fn load(
            &self,
            agora: AgoraId,
            slot: Slot,
            out: &mut [u8],
        ) -> Result<Option<usize>, ProtocolError> {
            let Some(value) = self.values.get(&(*agora.as_bytes(), slot)) else {
                return Ok(None);
            };
            let out = out.get_mut(..value.len()).ok_or(ProtocolError::Malformed)?;
            out.copy_from_slice(value);
            Ok(Some(value.len()))
        }

        fn delete(&mut self, agora: AgoraId, slot: Slot) -> Result<(), ProtocolError> {
            self.log.push(('d', slot));
            self.values.remove(&(*agora.as_bytes(), slot));
            Ok(())
        }
    }

    impl TestStore {
        fn holds(&self, agora: AgoraId, slot: Slot) -> bool {
            self.values.contains_key(&(*agora.as_bytes(), slot))
        }
    }

    fn key_store() -> SoftwareKeyStore {
        SoftwareKeyStore::new([0x5a; 32])
    }

    fn entropy(byte: u8) -> FreshEntropy {
        FreshEntropy::new([byte; 32])
    }

    #[cfg(feature = "provisional-algebraic-hash")]
    fn created(store: &mut TestStore, agora: AgoraId) -> Created {
        let mut pk = [0u8; 32];
        let mut binding = [0u8; 32];
        create(
            agora,
            &key_store(),
            store,
            entropy(0x44),
            entropy(0x22),
            &mut pk,
            &mut binding,
        )
        .expect("creation succeeds")
    }

    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn create_stores_the_three_durable_slots_and_returns_the_leaf() {
        let mut store = TestStore::default();
        let made = created(&mut store, AGORA_A);

        for slot in [Slot::CredentialKey, Slot::RootOpening, Slot::RootPublicKey] {
            assert!(store.holds(AGORA_A, slot), "{slot:?} was not stored");
        }

        // The commitment is exactly the leaf over the stored material.
        let mut pk = [0u8; 32];
        let len = store
            .load(AGORA_A, Slot::RootPublicKey, &mut pk)
            .unwrap()
            .unwrap();
        let expected = commit(
            &pk[..len],
            &CredentialKey::new([0x44; 32]),
            &RootOpening::new([0x22; 32]),
            &AGORA_A,
        );
        assert_eq!(made.commitment, expected);
        assert_eq!(made.root.binding, None, "the software backend claims none");
    }

    /// The atomicity contract: a failure part-way must leave no slot behind.
    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn create_unwinds_every_slot_a_failure_leaves_behind() {
        for allowed in 0..3 {
            let mut store = TestStore {
                stores_before_failure: Some(allowed),
                ..TestStore::default()
            };
            let mut pk = [0u8; 32];
            let mut binding = [0u8; 32];
            let result = create(
                AGORA_A,
                &key_store(),
                &mut store,
                entropy(0x44),
                entropy(0x22),
                &mut pk,
                &mut binding,
            );
            assert_eq!(result.unwrap_err(), ProtocolError::Unavailable);
            for slot in [Slot::CredentialKey, Slot::RootOpening, Slot::RootPublicKey] {
                assert!(
                    !store.holds(AGORA_A, slot),
                    "{slot:?} survived a failure after {allowed} stores"
                );
            }
        }
    }

    /// §16.1 at the lifecycle level: even the *same entropy*, replayed into two agoras by a
    /// hostile or broken host, yields unrelated credentials — by construction (0013), not
    /// because the entropy rule was followed.
    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn identical_entropy_in_two_agoras_yields_unrelated_credentials() {
        let mut store = TestStore::default();
        let first = created(&mut store, AGORA_A);
        let second = created(&mut store, AGORA_B);
        assert_ne!(first.commitment, second.commitment);
    }

    fn rolled(store: &mut TestStore, agora: AgoraId, epoch: u64, secret: u8) {
        let mut record = [0u8; 128];
        roll_epoch(
            agora,
            &key_store(),
            store,
            Epoch::new(epoch),
            entropy(secret),
            &[0xcc; 32],
            &mut record,
        )
        .expect("rollover succeeds");
    }

    #[test]
    fn roll_stores_key_certificate_and_cursor() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 5, 0xe1);

        assert!(store.holds(AGORA_A, Slot::EpochKey(Epoch::new(5))));
        assert!(store.holds(AGORA_A, Slot::EpochCursor));

        let mut buffer = [0u8; 128];
        let record = load_epoch_record(AGORA_A, &store, Epoch::new(5), &mut buffer)
            .unwrap()
            .expect("record is stored");
        assert_eq!(record.public_key, &[0xcc; 32]);

        // The stored signature is exactly the backend's signature over the canonical
        // payload — recomputable because the software backend is deterministic. The buffer
        // is generous rather than sized to the scheme: the stand-in's signature width is
        // deliberately unpinned here.
        let mut expected = [0u8; 128];
        let len = key_store()
            .sign_epoch_cert(
                &EpochCertPayload {
                    agora: AGORA_A,
                    epoch: Epoch::new(5),
                    epoch_public_key: &[0xcc; 32],
                },
                &mut expected,
            )
            .unwrap();
        assert_eq!(record.signature, &expected[..len]);
    }

    /// §9.1 / proposal 0007: however late the device wakes, ended epochs leave nothing
    /// usable behind.
    #[test]
    fn roll_sweeps_every_epoch_the_device_slept_through() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 3, 0xe1);
        rolled(&mut store, AGORA_A, 7, 0xe2);

        assert!(!store.holds(AGORA_A, Slot::EpochKey(Epoch::new(3))));
        assert!(!store.holds(AGORA_A, Slot::EpochCert(Epoch::new(3))));
        assert!(store.holds(AGORA_A, Slot::EpochKey(Epoch::new(7))));

        let swept: Vec<u64> = store
            .log
            .iter()
            .filter_map(|(op, slot)| match (op, slot) {
                ('d', Slot::EpochKey(e)) => Some(e.get()),
                _ => None,
            })
            .collect();
        assert_eq!(
            swept,
            vec![3, 4, 5, 6],
            "the sweep must cover the whole gap"
        );
    }

    /// Destruction is driven by the epoch ending, not by certifying a successor.
    #[test]
    fn discarding_without_certifying_still_destroys() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 3, 0xe1);
        discard_expired(AGORA_A, &mut store, Epoch::new(5)).expect("sweep succeeds");

        assert!(!store.holds(AGORA_A, Slot::EpochKey(Epoch::new(3))));
        assert!(!store.holds(AGORA_A, Slot::EpochCert(Epoch::new(3))));

        // The cursor still names the last certification, and a later roll is unaffected.
        rolled(&mut store, AGORA_A, 5, 0xe2);
        assert!(store.holds(AGORA_A, Slot::EpochKey(Epoch::new(5))));
    }

    #[test]
    fn rolling_backward_is_refused() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 7, 0xe1);
        let mut record = [0u8; 128];
        assert_eq!(
            roll_epoch(
                AGORA_A,
                &key_store(),
                &mut store,
                Epoch::new(5),
                entropy(0xe2),
                &[0xcc; 32],
                &mut record,
            ),
            Err(ProtocolError::Malformed)
        );
        assert!(
            store.holds(AGORA_A, Slot::EpochKey(Epoch::new(7))),
            "a refused roll must change nothing"
        );
    }

    /// The sweep bound: a corrupted epoch number is an error, not an unbounded delete loop.
    #[test]
    fn an_implausible_epoch_jump_is_refused() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 0, 0xe1);
        assert_eq!(
            discard_expired(AGORA_A, &mut store, Epoch::new(MAX_EPOCH_GAP + 2)),
            Err(ProtocolError::Malformed)
        );
    }

    /// §9.1: nothing can stop a member certifying twice in one epoch, so re-certifying is
    /// permitted and keeps the latest key.
    #[test]
    fn recertifying_the_same_epoch_overwrites() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 5, 0xe1);
        rolled(&mut store, AGORA_A, 5, 0xe2);
        let mut key = [0u8; 32];
        let len = store
            .load(AGORA_A, Slot::EpochKey(Epoch::new(5)), &mut key)
            .unwrap()
            .unwrap();
        assert_eq!(&key[..len], &[0xe2; 32]);
    }

    #[test]
    fn a_stored_tag_key_lands_in_its_epoch_slot() {
        let mut store = TestStore::default();
        store_tag_key(AGORA_A, &mut store, Epoch::new(4), &TagKey::new([0x77; 32]))
            .expect("store succeeds");
        assert!(store.holds(AGORA_A, Slot::TagKey(Epoch::new(4))));
    }

    #[test]
    fn epoch_record_decoding_is_strict() {
        let mut store = TestStore::default();
        rolled(&mut store, AGORA_A, 5, 0xe1);
        let mut buffer = [0u8; 128];
        let len = store
            .load(AGORA_A, Slot::EpochCert(Epoch::new(5)), &mut buffer)
            .unwrap()
            .unwrap();

        EpochRecord::decode(&buffer[..len]).expect("the stored record decodes");
        for cut in 0..len {
            assert!(
                EpochRecord::decode(&buffer[..cut]).is_err(),
                "a {cut}-byte prefix decoded"
            );
        }

        let mut trailing = buffer[..len].to_vec();
        trailing.push(0);
        assert_eq!(
            EpochRecord::decode(&trailing),
            Err(ProtocolError::Malformed)
        );
    }

    /// The full path-1 flow across two devices, per §9.3's ordering: the successor's root
    /// exists first, the old device authorizes, the successor completes.
    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn planned_migration_carries_the_credential_key_and_spends_the_old_leaf() {
        let mut old_device = TestStore::default();
        let old = created(&mut old_device, AGORA_A);

        // Successor generates its root first; its public key travels to the old device.
        let successor_keys = SoftwareKeyStore::new([0x5b; 32]);
        let mut successor_pk = [0u8; 32];
        let mut binding = [0u8; 32];
        let written =
            create_successor_root(AGORA_A, &successor_keys, &mut successor_pk, &mut binding)
                .expect("root creation succeeds");
        let successor_pk = &successor_pk[..written.public_key];

        // Old device authorizes and emits the handoff.
        let mut old_pk = [0u8; 64];
        let mut signature = [0u8; 64];
        let mut handoff_bytes = [0u8; 256];
        let len = authorize_migration(
            AGORA_A,
            &key_store(),
            &old_device,
            successor_pk,
            &mut old_pk,
            &mut signature,
            &mut handoff_bytes,
        )
        .expect("authorization succeeds");

        // Successor decodes and completes. The consumed leaf is no longer carried — it is
        // derived from the handoff's witness material, and must equal the leaf created.
        let handoff = MigrationHandoff::decode(&handoff_bytes[..len]).expect("handoff decodes");
        assert_eq!(
            commit(
                handoff.root_public_key,
                &handoff.credential_key,
                &handoff.root_opening,
                &AGORA_A,
            ),
            old.commitment
        );

        let mut new_device = TestStore::default();
        let migrated = complete_migration(
            AGORA_A,
            &mut new_device,
            &handoff,
            successor_pk,
            entropy(0x23),
        )
        .expect("migration completes");

        // The spend is the per-leaf migration nullifier over the carried key.
        assert_eq!(
            migrated.spend,
            nullifier::migration(&CredentialKey::new([0x44; 32]), &old.commitment, &AGORA_A)
        );
        assert_ne!(migrated.commitment, old.commitment);

        // The successor holds the same sk_cred, a fresh opening, its own root.
        let mut sk = [0u8; 32];
        new_device
            .load(AGORA_A, Slot::CredentialKey, &mut sk)
            .unwrap()
            .expect("sk_cred carried over");
        assert_eq!(sk, [0x44; 32]);
    }

    /// One leaf, one spend — but a lineage migrates more than once, and each consumed leaf
    /// spends its own nullifier (§9.3, proposal 0015).
    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn each_migration_of_a_lineage_spends_its_own_nullifier() {
        // Varying the old opening varies the derived consumed leaf — two migrations of one
        // lineage, two distinct spends.
        let sign = |opening: u8| {
            let handoff = MigrationHandoff {
                agora: AGORA_A,
                credential_key: CredentialKey::new([0x44; 32]),
                root_opening: RootOpening::new([opening; 32]),
                root_public_key: &[0x11; 32],
                migration_cert: b"cert",
            };
            let mut store = TestStore::default();
            complete_migration(AGORA_A, &mut store, &handoff, &[0x66; 32], entropy(0x23))
                .expect("migration completes")
                .spend
        };
        assert_ne!(sign(0xaa), sign(0xab));
    }

    /// A handoff must fail against the wrong agora before anything derives from it.
    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn a_handoff_for_another_agora_is_refused() {
        let handoff = MigrationHandoff {
            agora: AGORA_B,
            credential_key: CredentialKey::new([0x44; 32]),
            root_opening: RootOpening::new([0x22; 32]),
            root_public_key: &[0x11; 32],
            migration_cert: b"cert",
        };
        let mut store = TestStore::default();
        assert_eq!(
            complete_migration(AGORA_A, &mut store, &handoff, &[0x66; 32], entropy(0x23))
                .unwrap_err(),
            ProtocolError::Malformed
        );
        assert!(
            !store.holds(AGORA_A, Slot::CredentialKey),
            "a refused handoff stored something"
        );
    }

    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn authorizing_without_a_credential_is_unavailable() {
        let store = TestStore::default();
        let mut pk = [0u8; 64];
        let mut signature = [0u8; 64];
        let mut out = [0u8; 256];
        assert_eq!(
            authorize_migration(
                AGORA_A,
                &key_store(),
                &store,
                &[0x66; 32],
                &mut pk,
                &mut signature,
                &mut out,
            ),
            Err(ProtocolError::Unavailable)
        );
    }

    /// The phase's exit criterion, in one test: the full lifecycle — create, certify,
    /// roll, migrate — across two agoras, on the reference backend and the test store,
    /// with the same entropy fed to both memberships adversarially. No value derived in
    /// one agora may equal its counterpart in the other, and the migration in one must
    /// leave the other untouched.
    #[test]
    #[cfg(feature = "provisional-algebraic-hash")]
    fn the_full_lifecycle_runs_in_two_agoras_without_a_shared_value() {
        let mut store = TestStore::default();

        // Same entropy into both agoras — the negative class is construction, not conduct.
        let first = created(&mut store, AGORA_A);
        let second = created(&mut store, AGORA_B);
        assert_ne!(first.commitment, second.commitment);

        let mut pk_a = [0u8; 32];
        let mut pk_b = [0u8; 32];
        let len_a = store
            .load(AGORA_A, Slot::RootPublicKey, &mut pk_a)
            .unwrap()
            .unwrap();
        let len_b = store
            .load(AGORA_B, Slot::RootPublicKey, &mut pk_b)
            .unwrap()
            .unwrap();
        assert_ne!(
            &pk_a[..len_a],
            &pk_b[..len_b],
            "one root key served two agoras"
        );

        // Certify and roll in both, same epoch numbers, same entropy.
        for agora in [AGORA_A, AGORA_B] {
            rolled(&mut store, agora, 1, 0xe1);
            rolled(&mut store, agora, 2, 0xe2);
            assert!(!store.holds(agora, Slot::EpochKey(Epoch::new(1))));
        }
        let mut buf_a = [0u8; 128];
        let mut buf_b = [0u8; 128];
        let record_a = load_epoch_record(AGORA_A, &store, Epoch::new(2), &mut buf_a)
            .unwrap()
            .unwrap();
        let record_b = load_epoch_record(AGORA_B, &store, Epoch::new(2), &mut buf_b)
            .unwrap()
            .unwrap();
        assert_ne!(
            record_a.signature, record_b.signature,
            "one epoch certificate served two agoras"
        );

        // Migrate in A; B must be untouched and share nothing with the result.
        let successor_keys = SoftwareKeyStore::new([0x5b; 32]);
        let mut successor_pk = [0u8; 32];
        let mut binding = [0u8; 32];
        let written =
            create_successor_root(AGORA_A, &successor_keys, &mut successor_pk, &mut binding)
                .unwrap();
        let successor_pk = &successor_pk[..written.public_key];

        let mut old_pk = [0u8; 64];
        let mut signature = [0u8; 64];
        let mut handoff_bytes = [0u8; 256];
        let len = authorize_migration(
            AGORA_A,
            &key_store(),
            &store,
            successor_pk,
            &mut old_pk,
            &mut signature,
            &mut handoff_bytes,
        )
        .unwrap();
        let handoff = MigrationHandoff::decode(&handoff_bytes[..len]).unwrap();

        let mut new_device = TestStore::default();
        let migrated = complete_migration(
            AGORA_A,
            &mut new_device,
            &handoff,
            successor_pk,
            entropy(0x23),
        )
        .unwrap();

        // The spend an identical adversarial migration in B would produce is unrelated.
        let consumed = commit(
            handoff.root_public_key,
            &handoff.credential_key,
            &handoff.root_opening,
            &AGORA_A,
        );
        let spend_in_b = nullifier::migration(&CredentialKey::new([0x44; 32]), &consumed, &AGORA_B);
        assert_ne!(migrated.spend, spend_in_b);
        assert_ne!(migrated.commitment, second.commitment);
        assert!(
            store.holds(AGORA_B, Slot::CredentialKey),
            "a migration in one agora touched another"
        );
        assert!(store.holds(AGORA_B, Slot::EpochKey(Epoch::new(2))));
    }

    #[test]
    fn fresh_entropy_does_not_leak_through_debug() {
        let rendered = format!("{:?}", entropy(0xab));
        assert!(!rendered.contains("ab"), "entropy leaked: {rendered}");
        assert!(rendered.contains("redacted"), "{rendered}");
    }
}
